export const defaultSongs = [
  "rCYXH4CYP3I",
  "7NOSDKb0HlU",
  "n61ULEU7CO0",
  "tfBVp0Zi2iE",
  "jfKfPfyJRdk",
  "tfUPbO_vGzM",
  "QwXHcgZUnFI",
  "ehTuatSx5Wc",
  "5yx6BWlEVcY",
  "A6fjHQ2ZwZA",
  "apCom1TeTiA",
  "ejPxNyktUXU",
  "wA0C0uRxSaE",
  "q0BVR5jRXxE",
];
