export const defaultSongs = [
  "bJUO1WnjXQY",
  "HDhR2Yhnvfo",
  "n61ULEU7CO0",
  "tfBVp0Zi2iE",
  "jfKfPfyJRdk",
  "MCkTebktHVc",
  "XDh0JcxrbPM",
  "kgx4WGK0oNU",
  "5yx6BWlEVcY",
  "cqFHIB0JQxc",
  "IjMESxJdWkg",
  "-5KAN9_CzSA",
  "wA0C0uRxSaE",
  "q0BVR5jRXxE",
];
